### ISSUE TITLE
Can't get the container to work

### ISSUE THREAD

**Issue by rodgzilla** [lvm/tida1vm#1]
Hello,

I would like to get into livecoding using this docker container.

I followed this procedure from the README:

```
$ git clone https://github.com/lvm/tida1vm
$ cd tida1vm
$ git checkout 0.9
$ docker build -t tida1vm-0.9 .
$ docker run -ti --rm --net=host --name tida1vm lvm23/tida1vm:0.9
```

Everything got installed without error message. 

I then run Emacs and when I try to run Tidal code I get this message in the *tidal* buffer:

```
oops sendBuf: does not exist (Connection refused)
```

I tried to google what might be the cause of this error but did not manage to find a solution.

Could you help me?

**Comment by lvm** [comment]
Hi, 
sorry for the late response.

Do you have SuperCollider running? (not inside docker, but in the _host_/your-computer)
That error is because tidal can't connect to either classic-dirt or superdirt.

**Comment by lvm** [comment]
Since i got no response, will close this issue. Reopen if you still need assistance.
